wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off -P Q0_public/ http://archive.stsci.edu/pub/kepler/lightcurves/tarfiles/Q0_public/
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off -P Q1_public/ http://archive.stsci.edu/pub/kepler/lightcurves/tarfiles/Q1_public/
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off -P Q2_public/ http://archive.stsci.edu/pub/kepler/lightcurves/tarfiles/Q2_public/
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off -P Q3_public/ http://archive.stsci.edu/pub/kepler/lightcurves/tarfiles/Q3_public/
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off -P Q4_public/ http://archive.stsci.edu/pub/kepler/lightcurves/tarfiles/Q4_public/
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off -P Q5_public/ http://archive.stsci.edu/pub/kepler/lightcurves/tarfiles/Q5_public/
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off -P Q6_public/ http://archive.stsci.edu/pub/kepler/lightcurves/tarfiles/Q6_public/
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off -P Q7_public/ http://archive.stsci.edu/pub/kepler/lightcurves/tarfiles/Q7_public/
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off -P Q8_public/ http://archive.stsci.edu/pub/kepler/lightcurves/tarfiles/Q8_public/
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off -P Q9_public/ http://archive.stsci.edu/pub/kepler/lightcurves/tarfiles/Q9_public/
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off -P Q10_public/ http://archive.stsci.edu/pub/kepler/lightcurves/tarfiles/Q10_public/
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off -P Q11_public/ http://archive.stsci.edu/pub/kepler/lightcurves/tarfiles/Q11_public/
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off -P Q12_public/ http://archive.stsci.edu/pub/kepler/lightcurves/tarfiles/Q12_public/
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off -P Q13_public/ http://archive.stsci.edu/pub/kepler/lightcurves/tarfiles/Q13_public/
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off -P Q14_public/ http://archive.stsci.edu/pub/kepler/lightcurves/tarfiles/Q14_public/
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off -P Q15_public/ http://archive.stsci.edu/pub/kepler/lightcurves/tarfiles/Q15_public/
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off -P Q16_public/ http://archive.stsci.edu/pub/kepler/lightcurves/tarfiles/Q16_public/
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off -P Q17_public/ http://archive.stsci.edu/pub/kepler/lightcurves/tarfiles/Q17_public/